### ISSUE TITLE
Project IDs should be sequential so that Users can perform a search based on Project IDs and also identify a Project by Project ID

### ISSUE THREAD

**Issue by nehadgautam** [perpetualintelligence/pidotapp-bugs#38] opened 2020-05-14 15:26 UTC
Currently, Project IDs are not readable/random. Project name is not sufficient to identify a Project. There could be two Projects with similar names. Project IDs can help uniquely identify a Project but currently this is not possible since Project IDs are random.

![image](https://user-images.githubusercontent.com/65241627/81952715-74282b00-9624-11ea-82f8-53798615c637.png)

**Comment by perpetualintelligence** [comment] 2020-05-17 05:55
@nehadgautam This behavior is by design. The Ids for all storable objects are auto generated and they need to unique in the context of your business account.  If you use the Perpetual Intelligence web application then all IDs will be generated as **short GUIDs and this behavior cannot be changed.** 

You can however use the API and set your own sequential IDs when you create translation projects and pages. Make sure they are unique in the context of your business account.

Search or find based on project Id is in our release plan for Jun-2020.

Closing the issue...

**Closed by perpetualintelligence** 2020-05-17 05:55 UTC
Labels: by design, wontfix
